package jto.processing.sketch.mapper;

import processing.core.PApplet;
import processing.core.PGraphics;

public abstract class AbstractCyclicSketch implements Sketch {

    protected PApplet parent;
    protected PGraphics graphics;
    protected boolean autoGenerated;

    public void setParent(PApplet parent) {
        this.parent = parent;
    }

    public void setGraphics(PGraphics graphics) {
        this.graphics = graphics;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Sketch)) {
            return false;
        }
        Sketch sketch = (Sketch) object;
        return this.getName().equals(sketch.getName());
    }

    @Override
    public String getName() {
        return this.getClass().getSimpleName();
    }

    @Override
    public PGraphics getPGraphics() {
        return graphics;
    }

    @Override
    public int hashCode() {
        return this.getName().hashCode();
    }

    @Override
    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    @Override
    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

}
